package com.example.jakaceh;

import java.util.ArrayList;
import java.util.List;

public class Daftar {
    public static final List<Wisata> wisata = new ArrayList<Wisata>() {
        {
            add(new Wisata("Masjid Baiturrahman", "Masjid Raya Baiturrahman merupakan peninggalan Kerajaan Aceh yang menjadi simbol agama, budaya, dan perjuangan masyarakat Aceh. Pasalnya...", R.drawable.baiturrahman, 5.0F,
                    "Masjid Raya Baiturrahman memiliki lembaran sejarah dan nilai yang tinggi bagi rakyat Aceh. Hal ini karena sejak Sultan Iskandar Muda memimpin hingga sekarang masih tetap berdiri megah. \n" +
                            "Transformasi pembangunan Masjid Baiturrahman ini bervariasi.  Awal dibangun, masjid ini berkubah segi empat. Saat sekutu (penjajah Belanda) tiba di Aceh dan melakukan penyerangan ke Koetaraja (Banda Aceh saat ini), masjid inipun juga ikut hangus karena dibakar. Sontak Rakyat Aceh tak tinggal diam melainkan semangat porjuangan semakin tinggi dan memanas untuk menyerang sekutu. Masyarakat Aceh pun melakukan perlawanan lebih sigap terhadap Belanda pada 10 April 1873.\n" +
                            "Perang ini dianggap sengit, karena tempat ibadah masyarakat Aceh dihancurkan. Dari pertempuran ini, pada tanggal 14 April 1873, Belanda kehilangan seorang panglimanya yakni Major General Johan Harmen Rudolf Köhler.\n" +
                            "Setelah melakukan komunikasi, pihak Belanda berjanji akan membangun kembali masjid tersebut. Hal itu disampaikan oleh Jenderal Van Sweiten atas perintah Gubernur Jenderal Van Lansberge. Janji pembangunan tersebut baru terlaksana pada empat tahun setelah kejadian pembakaran, yaitu 1879 dan selesai tahun 1881.\n" +
                            "Referensi yang dihimpun Readers.ID  menunjukan pembangunan itu terjadi dimasa pemerintahan sultan Aceh yang terakhir, yaitu Muhammad Daud Syah, dengan desain Gerrit Bruns, seorang arsitek berdarah Belanda.\n" +
                            "Tranformasi pondasi dan bentuk masjid pun berubah jauh. Belanda membangun masjid dengan menggunakan kubah seperti saat sekarang ini, namun hanya berkubah satu. Tahap selanjutnya dilakukan perluasan dan penambahan bangunan hingga kubah pun bertambah. Diketahui, kubah hitam dibangun dari sirap kayu keras yang digabung menjadi ubin.\n" +
                            "Tanggal 26 Desember 2004, Aceh pun kembali berduka dengan hadirnya tsunami Aceh, diawal kepemimpinan kepala negara Susilo Bambang Yudhoyono atau SBY. Masjid ini pun masih tumbuh kokoh dan berdiri diantara puing-puing bangunan lainnya yang sudah rata dengan tanah.\n" +
                            "Renovasi masjid ini kembali terjadi beberapa tahun belakangan. Arsitek masjid ini kemudian diadaptasi oleh L.P. Luijks, yang juga mengawasi pekerjaan konstruksi yang dilakukan oleh kontraktor Lie A Sie. Desain yang dipilih adalah gaya kebangkitan Mughal, yang dicirikan oleh kubah besar dengan menara-menara."));
            add(new Wisata("Museum Tsunami", "Museum Tsunami didirikan untuk mengenang peristiwa tsunami 2004. Dokumentasi foto dan audio visual tentang dampak peristiwa dahsyat itu... ", R.drawable.tsunami, 4.9F,
                    "Museum Tsunami didirikan untuk mengenang peristiwa tsunami 2004. Dokumentasi foto dan audio visual tentang dampak peristiwa dahsyat itu dapat dilihat di museum berbentuk rumah panggung khas Aceh ini. Tur audio visual salah satu hal wajib dinikmati jika mengunjungi Museum Tsunami. Pengunjung akan melewati beberapa ruang yang merefleksikan pengalaman korban tsunami. Mulai dari Space of Fear, Space of Memory, Space of Sorrow, Space of Confuse, dan Space of Hope.\n" +
                            "Sebuah destinasi dark tourism dengan desain bangunan berlantai empat yang futuristik. Museum Tsunami didirikan untuk mengenang peristiwa tsunami 2004. Dokumentasi foto dan audio visual tentang dampak peristiwa dahsyat itu dapat dilihat di museum berbentuk rumah panggung khas Aceh ini. Tur audio visual salah satu hal wajib dinikmati jika mengunjungi Museum Tsunami. Pengunjung akan melewati beberapa ruang yang merefleksikan pengalaman korban tsunami. Mulai dari Space of Fear, Space of Memory, Space of Sorrow, Space of Confuse, dan Space of Hope."));
            add(new Wisata("Museum Aceh", "Museum Aceh didirikan pada masa pemerintahan Hindia Belanda, yang pemakaiannya diresmikan oleh Gubernur Sipil dan Militer Belanda di Aceh...", R.drawable.aceh, 4.5F,
                    "Museum didirikan pada masa pemerintahan Hindia Belanda, yang pemakaiannya diresmikan oleh Gubernur Sipil dan Militer Aceh Jenderal H.N.A. Swart pada tanggal 31 Juli 1915. Pada waktu itu yang didirikannya berupa sebuah yang didirikan rumah tradisional Aceh (Rumoh Aceh). Yang didirikan tersebut berasal dari Paviliun Aceh yang ditaruh di arena Pameran Kolonial (De Koloniale Tentoonsteling) di Semarang pada tanggal 13 Agustus - 15 November 1914.\n" +
                            "Pada waktu penyelenggaraan pameran di Semarang, paviliun Aceh memamerkan koleksi-koleksi yang beberapa luhur merupakan milik pribadi F.W. Stammeshaus, yang pada tahun 1915 menjadi kurator Museum Aceh pertama. Selain koleksi milik Stammeshaus, juga dipamerkan koleksi-koleksi berupa benda-benda pusaka dari pembesar Aceh, sehingga dengan demikian paviliun Aceh merupakan paviliun yang sangat komplit koleksinya.\n" +
                            "Pada pameran itu paviliun Aceh berhasil memperoleh 4 medali emas, 11 perak, 3 perunggu, dan piagam penghargaan kepada paviliun terbaik. Keempat medali emas tersebut diberikan kepada pertunjukan, boneka-boneka Aceh, etnografika, dan mata uang; perak kepada pertunjukan, foto, dan peralatan rumah tangga. Karena keberhasilan tersebut Stammeshaus mengusulkan kepada Gubernur Aceh supaya paviliun tersebut dibawa kembali ke Aceh dan menjadi sebuah museum. Ide ini diterima oleh Gubernur Aceh Swart. Atas prakarsa Stammeshaus, paviliun Aceh itu dikembalikan ke Aceh, dan pada tanggal 31 Juli 1915 diresmikan kepada Aceh Museum, yang berlokasi di sebelah timur Blang Padang di Kutaraja (Banda Aceh sekarang). Museum ini berada di bawah tanggungjawab penguasa sipil dan militer Aceh F.W. Stammeshaus kepada kurator pertama.\n" +
                            "Setelah Indonesia merdeka, Museum Aceh menjadi milik Pemerintah Daerah Aceh yang pengelolaannya diserahkan kepada Pemerintah Daerah Tk. II Banda Aceh. Pada tahun 1969 atas prakarsa Teuku Hamzah Bendahara, Museum Aceh dipindahkan dari tempatnya yang lama (Blang Padang) ke tempatnya yang sekarang ini, di Jalan Sultan Alaidin Mahmudsyah pada tanah seluas 10.800 m2. Setelah pemindahan ini pengelolaannya diserahkan kepada Badan Pembina Rumpun Iskandar Muda (BAPERIS) Pusat."));
            add(new Wisata("Kompleks Makam Raja-Raja", "Kompleks Makam Putroe Ijo diperkirakan sebagai kompleks peristirahatan terakhir seorang putri sultan Kesultanan Aceh Darussalam. Putri tersebut dinamakan Putroe Ijo...", R.drawable.makamraja, 5.0F,
                    "Kompleks Makam Putroe Ijo diperkirakan sebagai kompleks peristirahatan terakhir seorang putri sultan Kesultanan Aceh Darussalam. Putri tersebut dinamakan Putroe Ijo karena kecantikan dan keindahan fisiknya. Di dalam kompleks ini, selain makam Putroe Ijo juga terdapat makam lainnya dari anggota Kesultanan Aceh Darussalam.\n" +
                            "Mengenai sosok Putroe Ijo (Putri Hijau) sendiri berkembang banyak cerita di kalangan masyarakat dan sejarawan. Namun mereka sepakat bahwa Putroe Ijo merupakan keturunan dari seorang raja.\n" +
                            "Di luar kompleks makam raja-raja di Aceh, Gampong Pande juga menyimpan sejumlah hal lainnya, seperti pohon bakau yang tumbuh di tambak masyarakat, tambak kepiting, dan pada tahun 2013 lalu warga setempat menemukan koin-koin emas dan pedang peninggalan VOC (Belanda) di dalam tambak. Menandakan gampong ini kaya sejarah. Ada yang sudah terungkap, ada juga yang belum."));
        }
    };
}
